# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.18.180301'

RELEASE_GIT_HEAD = 'aa6e10176bb7c171cd2765cc395b4debea4790ed'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'power12317/yt-dlp'

ORIGIN = 'power12317/yt-dlp'

_pkg_version = '2024.10.18.180301'
